const products=[
{id:1,name:'Pink Romance',category:'Bouquet',price:1599,img:'assets/pink-bouquet.svg',desc:'A lovely bouquet of pink roses that expresses love, gratitude and sweet memories.'},
{id:2,name:'Sunset Tulips',category:'Bouquet',price:1199,img:'assets/sunset-bouquet.svg',desc:'Warm, cheerful blooms perfect for birthdays and celebrations.'},
{id:3,name:'Lavender Dreams',category:'Bouquet',price:1499,img:'assets/lavender-bouquet.svg',desc:'Soft lavender flowers for a calm and elegant gift.'},
{id:4,name:'Love in Bloom',category:'Gift',price:1099,img:'assets/love-box.svg',desc:'A romantic flower gift prepared for someone special.'},
{id:5,name:'Tulip Gift Box',category:'Gift',price:1699,img:'assets/sunset-bouquet.svg',desc:'A charming gift box with fresh blooms and a sweet finish.'},
{id:6,name:'Baby Breath',category:'Bouquet',price:999,img:'assets/lavender-bouquet.svg',desc:'Simple and delicate blooms for a thoughtful surprise.'}
];
let cart=JSON.parse(localStorage.getItem('bloomcart'))||[];
const peso=n=>'₱'+n.toLocaleString('en-PH');
function save(){localStorage.setItem('bloomcart',JSON.stringify(cart));count();}
function count(){document.querySelectorAll('.badge').forEach(x=>x.textContent=cart.reduce((a,b)=>a+b.qty,0));}
function add(id,custom=''){const p=products.find(x=>x.id===id);const key=id+'-'+custom;const old=cart.find(x=>x.key===key);if(old)old.qty++;else cart.push({...p,key,qty:1,custom});save();alert(p.name+' added to cart 🌷');}
function cards(list,id){const el=document.getElementById(id);if(!el)return;el.innerHTML=list.map(p=>`<article class="card"><a href="product.html?id=${p.id}"><div class="card-img"><img src="${p.img}" alt="${p.name}"></div></a><div class="card-info"><span class="tag">${p.category}</span><h3>${p.name}</h3><p>${p.desc}</p><div class="price">${peso(p.price)}</div><button class="mini" onclick="add(${p.id})">ADD TO CART</button> <a class="mini" href="customize.html?id=${p.id}">CUSTOMIZE</a></div></article>`).join('');}
function productPage(){const box=document.getElementById('productDetail');if(!box)return;const id=Number(new URLSearchParams(location.search).get('id'))||1;const p=products.find(x=>x.id===id)||products[0];box.innerHTML=`<div class="detail-img"><img src="${p.img}" alt="${p.name}"></div><div><span class="tag">${p.category}</span><h1>${p.name}</h1><div class="price">${peso(p.price)}</div><p>${p.desc}</p><p>Choose your customization and make your gift extra special.</p><button class="btn" onclick="add(${p.id})">ADD TO CART</button><a class="text-btn" style="margin-left:16px" href="customize.html?id=${p.id}">CUSTOMIZE →</a></div>`;}
function shop(){const input=document.getElementById('search'),filter=document.getElementById('filter');if(!input)return;function run(){const q=input.value.toLowerCase(),c=filter.value;cards(products.filter(p=>(c==='all'||p.category===c)&&(p.name.toLowerCase().includes(q)||p.desc.toLowerCase().includes(q))),'shopGrid')}input.addEventListener('input',run);filter.addEventListener('change',run);run();}
function cartPage(){const box=document.getElementById('cartList'),sum=document.getElementById('summary');if(!box)return;if(!cart.length){box.innerHTML='<div class="form-card"><h2>Your cart is empty 🌷</h2><p>Find a beautiful gift for someone special.</p><a class="btn" href="shop.html">SHOP NOW</a></div>';sum.innerHTML='';return}box.innerHTML=cart.map((p,i)=>`<div class="cart-item"><img src="${p.img}"><div><b>${p.name}</b><p>${p.custom||''}</p><span class="price">${peso(p.price)}</span></div><div class="qty"><button onclick="change(${i},-1)">−</button><b>${p.qty}</b><button onclick="change(${i},1)">+</button><button class="mini" onclick="removeItem(${i})">Remove</button></div></div>`).join('');const total=cart.reduce((a,b)=>a+b.price*b.qty,0);sum.innerHTML=`<div class="summary"><h2>Order Summary</h2><p>${cart.reduce((a,b)=>a+b.qty,0)} item(s)</p><h2>Total: ${peso(total)}</h2><a class="btn" href="checkout.html">CHECKOUT</a></div>`;}
function change(i,n){cart[i].qty+=n;if(cart[i].qty<1)cart.splice(i,1);save();cartPage()}function removeItem(i){cart.splice(i,1);save();cartPage()}
document.addEventListener('DOMContentLoaded',()=>{count();cards(products.slice(0,3),'featuredGrid');shop();productPage();cartPage();const form=document.getElementById('customForm');if(form){const id=Number(new URLSearchParams(location.search).get('id'))||1;form.addEventListener('submit',e=>{e.preventDefault();const c=`${flowerColor.value} flowers • ${arrangement.value} • ${wrap.value} wrap • ${ribbon.value} ribbon • Message: ${message.value||'None'}`;add(id,c);location.href='cart.html'})}const checkout=document.getElementById('checkoutForm');if(checkout)checkout.addEventListener('submit',e=>{e.preventDefault();if(!cart.length){alert('Your cart is empty.');return}alert('Order placed successfully! Thank you for choosing BloomCart 🌸');cart=[];save();location.href='index.html'});});